MetaCortex.addCortex validate name parameter`
Thought I could use an existing cortex instance like so:

```
memcortex = s_cortex.openurl("ram://")
metacortex = s_cortex.MetaCortex()
metacortex.addCortex("test.mem", memcortex)
```

Didn't get any exceptions, but also didn't get any results when I started querying.

I realize this is user error, but some validation might be useful? totally up to you.

Incidentally, I was surprised when I hooked into "meta:cortex:exc" --- I had an infinite loop on my hands, due to the exception handler in `_tryAddCorUrl`. I see why it happens, but I didn't have a good way to stop it besides resetting everything. Something to think about when there's free time.

```
('log', (('meta:cortex:exc', {'name': 'test.mem', 'exc': AttributeError("Cortex instance has no attribute 'find'",)}),), {})
```